### ISSUE TITLE
Praca domowa 2: "Support for the experimental syntax 'decorators-legacy' isn't currently enabled (1:1)"

### ISSUE THREAD

**Issue by wfabjanczuk** [daftcode/daftacademy-frontend_levelup-spring2019#1]
Cześć, zacząłem drugą pracę domową i próbowałem skonfigurować Sassa w JSie zgodnie z tym co było na ostatniej prezentacji. Dostaję błąd: "Support for the experimental syntax 'decorators-legacy' isn't currently enabled (1:1)" przy linijce "@import 'main.sass'" w index.js. Może ktoś miał już podobny problem i go rozwiązał?

**Comment by wfabjanczuk** [comment]
Rozwiązałem to zmieniając importowanie na "import './main.sass'" i instalując dodatkowo paczkę "node-sass". Czy tak może być, czy preferujecie inne rozwiązanie?

**Comment by m8ms** [comment]
Cześć!
Faktycznie - w prezentacji są dwa błędy!

1. Nie powinno być: 
```javascript
@import 'main.sass'
```

Tylko: 
```javascript
import 'main.sass'
```

2. Na liście paczek które trzeba zainstlować nie znalazł się sam SASS. Doinstalujcie:
```bash
npm i -s node-sass
```

**Comment by ibaczewska** [comment]
Czy po zrobieniu tej konfiguracji style powinny być w oddzielnym pliku czy dalej będą w w znaczniku <style> w sekcji head?

**Comment by m8ms** [comment]
To zależy, czy użyłaś MiniCssExtractPlugin.
Konfiguracja z tego slajdu: 

Https://m8ms.github.io/stylowanie_bardziej/#/3/1 

przy założeniu, że `isProducion = true` powinna wygenerować zewnętrzny plik CSS i załączyć go do HTML automatycznie (jeśli używasz webpack-html-plugin, jak we właściwym rozwiązaniu poprzedniego zadania),

Albo inaczej: `MiniCssExtractPlugin` wraz z loaderem powinien być załączony tylko do `webpack.config.prod.js`

**Comment by ibaczewska** [comment]
```
var path = require('path');
var HtmlWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const isProduction = process.env.NODE_ENV === 'production';

module.exports = {
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'main.js'
  },
  mode: 'production', 
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env']
          }
        }
      },
      {
        test: /\.s(a|c)ss$/,
        use: [
          isProduction
            ? MiniCssExtractPlugin.loader
            : { loader: 'style-loader', options: { sourceMap: true } },
          { loader: 'css-loader', options: { sourceMap: isProduction } },
          { loader: 'postcss-loader', options: { sourceMap: isProduction } },
          { loader: 'sass-loader', options: { sourceMap: isProduction } }
        ]
      }
    ]
  },
  plugins: [
    new MiniCssExtractPlugin({
      // Options similar to the same options in webpackOptions.output; optional
      filename: '[name].css',
      chunkFilename: '[id].css'
    }),
    new HtmlWebpackPlugin()
  ]
};
```


to jest moja konfiguracja w webpack.config.js.
W package.json, oprócz nowych paczek, to nic się nie zmieniło, ale wnioskuję, że powinnam stworzyć plik webpack.config.prod.js i tam wrzucić konfigurację ze slajdu i w package.json stworzyć nowy script, coś w tym stylu:

```
"start": "webpack --config webpack.config.js",
    "build": "webpack --config webpack.config.prod.js"
```
Coś takiego? 

Za porzednią pracę domową dostałam 5 pkt, więc była ok ;)

**Comment by m8ms** [comment]
Nie musisz mieć oddzielnie pliku webpack.config.prod.js. Jeśli w jednym pliku sterujesz flagą, czy coś jest production czy nie, to drugi jest niepotrzebny (ale wtedy sYbko wkrada się bałagan). Pamiętaj też, że "sourceMapy" chcesz mieć w środowisku developerskim, a nie na produkcji, więc raczej `{ sourceMap: !isProduction }` (na wykładzie zwracałem uwagę, że tam jest błąd)

**Comment by ibaczewska** [comment]
Ok, dzięki :)
