### ISSUE TITLE
Przypisanie generatora do zmiennej

### ISSUE THREAD

**Issue by Citrix94** [daftcode/daftacademy-frontend_levelup-spring2019#5]
Cześć, po stworzeniu generatorów, jeden z nich, który inicjuje cały proces liczenia wrzuciłem do zmiennej: `const startGenerators = generatorOfSeconds();` i dopiero to wstawiłem do setIntervala z dopiskiem .next() Pytanie czy koniecznie muszę tak robić i czy mogę pominąć przypisywanie tego generatora do zmiennej i od razu wrzucić go do setInterval? Poniżej przykład o co mi dokładnie chodzi (tak też działa).

![Screenshot_4](https://user-images.githubusercontent.com/23727114/55822553-25928e00-5b00-11e9-8a3f-d67abc73b5c1.jpg)

Pozdrawiam!

**Comment by AndrzejChemerys** [comment]
Hej, moim zdaniem, to chyba jest odpowiedź: 

![generator](https://user-images.githubusercontent.com/38627095/55889175-f2f49e00-5bb0-11e9-9425-1d9ce2fe9ef6.JPG)

Polecam też cały artykuł:

https://www.nafrontendzie.pl/generatory-es6-podstawy

**Comment by Citrix94** [comment]
Ostatecznie tak właśnie zrobiłem. Dzięki wielkie :)
